In [1]:
# ez most tökéletesen működik 2024.05.10. 11:25
# új módon, importált TZ függvényekkel

###Tedd elérhetővé a "df_EFC_output.csv és df_CZ_output.csv" és "TZ_functions.py" fájlokat
Ha Google Colabban futtatod, töltsd fel és csomagoltasd ki a "Flyball_input.zip" fájlt. Ha nem abban, lépd át ezeket a cellákat.

In [2]:
######### 240502 ######## Google Colab-ba fájlok feltöltése
from google.colab import files
import os

# Minden korábbi fájl és mappa törlése a Colab környezetben
files_and_folders = os.listdir()
for item in files_and_folders:
    if os.path.isfile(item):
        os.remove(item)

# Fájlok feltöltése
uploaded_files = files.upload()

# A feltöltött fájlok neveinek kinyerése
file_name = list(uploaded_files.keys())[0]

Saving Flyball_input.zip to Flyball_input.zip


In [3]:
### 240502 ### Google Colab-ban ZIP file kicsomagolása
from zipfile import ZipFile

with ZipFile(file_name, 'r') as zipfile2:
    zipfile2.extractall()
    print('Kicsomagolt fájlok:')
    for name in zipfile2.namelist():
        print(name)
    print('Done')

Kicsomagolt fájlok:
df_EFC_output.csv
df_CZ_output.csv
Wild_Runners_Flyball_Team_kutyak_alapadatai.xlsx
FLYBALLCZ_versenyadatok.xlsx
EFC_versenyadatok.xlsx
TZ_functions.py
df_EFC_CZ_track_good-date.csv
df_WRFT_output.csv
df_events.csv
df_EFC_CZ_post_analyzing_merged.csv
df_EFC_CZ_Weather.csv
Done


# alap importok és mindenféle megjelenítési beállítások, kikommentezve igény szerint:

In [4]:
import seaborn as sns
import numpy as np
import pandas as pd
import os
import shutil
sns.set(style="ticks")
seed=42
np.random.seed(seed)
#maximális oszlopszám megjelenítése
pd.options.display.max_columns = 20

In [5]:
from IPython.display import display, HTML
import numpy as np  # Új sor: NumPy importálása
import pandas as pd

# Beállítások
pd.set_option('display.max_rows', False)           # Az összes sor megjelenítése
pd.set_option('display.max_colwidth', None)        # Teljes méretű szöveges oszlopok
pd.set_option('display.expand_frame_repr', False)  # DataFrame vízszintes kiterjesztése kikapcsolva
pd.set_option('display.max_columns', 0)            # Az összes oszlop megjelenítése

In [6]:
display(HTML("<style>.container { width:100% !important; }</style>"))

In [7]:
pd.options.display.max_colwidth =300

# SAJÁT FÜGGVÉNYEK:

In [8]:
# betöltöm a 'TZ_functions.py' fájlban található saját gyártású, rendszeresen használt függvényeket
get_ipython().run_line_magic('run', 'TZ_functions.py')

 ############### ADATDOKI függvényei   ############### 
 ############### TZ_functions.py       ############### 
 ############### version = 2024.05.11. ############### 
A li() függvény listázásnál, legyen alapértelmezett a sorok száma?
 0 = ne legyen, azaz listázáskor rákérdez. Vagy szám = ennyi sort listáz rákérdezés nélkül. ("enter" változó)9


In [9]:
import pandas as pd

# DataFrame beolvasása CSV fájlból
df_EFC = pd.read_csv("df_EFC_output.csv")

# Az adatok megjelenítése
di(df_EFC.head())

In [10]:
dinfo(df_EFC)


DataFrame oszlopainak statisztikái:


In [11]:
# kicsit ismerkedtem az adatokkal
li(df_EFC)

használat: li(df)  # Használja az 'enter' változó értékét ha létezik és nagyobb mint 0, különben az összes sort megjeleníti vagy li(df, -1)


In [12]:
# kiíratom hány egyedi helyszín van.
luv(df_EFC, columns=["event_place"]) #luv(dataframe, list_values=10, columns=None, dtype="all", search_value=None) = list_unique_values

PARAMÉTEREZÉS: luv(dataframe, list_values=10, columns=["column1", "column2", ...], dtype="all/object/int64/float64/datetime64", search_value="valami")  = list_unique_values(dataframe)
Egyedi értékek a(z) 'event_place' 'oszlopban', (melynek típusa: object) (összesen: 4 db) (sorok száma: 1176)


Sorok száma: 1176



In [13]:
list_unique_values(df_EFC, columns=["W/L/T"], search_value="T"	) # ezzel statisztikáztam kicsit

PARAMÉTEREZÉS: luv(dataframe, list_values=10, columns=["column1", "column2", ...], dtype="all/object/int64/float64/datetime64", search_value="valami")  = list_unique_values(dataframe)
Egyedi értékek a(z) 'W/L/T' 'oszlopban', (melynek típusa: object) (összesen: 1 db) (sorok száma: 1176)


Sorok száma: 1176



In [14]:
list_unique_values(df_EFC, columns=["who"], list_values=100	) # ezzel statisztikáztam kicsit

PARAMÉTEREZÉS: luv(dataframe, list_values=10, columns=["column1", "column2", ...], dtype="all/object/int64/float64/datetime64", search_value="valami")  = list_unique_values(dataframe)
Egyedi értékek a(z) 'who' 'oszlopban', (melynek típusa: object) (összesen: 87 db) (sorok száma: 1176)


Sorok száma: 1176



In [15]:
# Új oszlopnevek definiálása, egységesítés céljából
new_column_names = {
    'sorsz': 'sorsz',
    'Division': 'division',
    'when': 'when',
    'who': 'who',
    'with who': 'with_who',
    'total time': 'total_time',
    'W/L/T': 'W/L/T',
    'Hurdles': 'hurdles',
    'name': 'name',
    'start': 'start',
    '1.dog': '1_dog',
    'name.1': 'name_1',
    'chng': 'chng',
    '2.dog': '2_dog',
    'name.2': 'name_2',
    'chng.1': 'chng_1',
    '3.dog': '3_dog',
    'name.3': 'name_3',
    'chng.2': 'chng_2',
    '4.dog': '4_dog',
    'event_place': 'event_place'
}

# Oszlopnevek átnevezése
df_EFC.rename(columns=new_column_names, inplace=True)
di(df_EFC.head())

In [16]:
import pandas as pd

# DataFrame beolvasása CSV fájlból
df_CZ = pd.read_csv("df_CZ_output.csv")

# Az adatok megjelenítése
di(df_CZ.head())

In [17]:
dinfo(df_CZ)


DataFrame oszlopainak statisztikái:


In [18]:
luv(df_CZ, columns=["event_place"]) #luv(dataframe, list_values=10, columns=None, dtype="all", search_value=None) = list_unique_values

PARAMÉTEREZÉS: luv(dataframe, list_values=10, columns=["column1", "column2", ...], dtype="all/object/int64/float64/datetime64", search_value="valami")  = list_unique_values(dataframe)
Egyedi értékek a(z) 'event_place' 'oszlopban', (melynek típusa: object) (összesen: 12 db) (sorok száma: 7397)


Sorok száma: 7397



In [19]:
li(df_CZ, 1000)

In [20]:
# Új oszlopnevek definiálása
new_column_names = {
    'sorsz': 'sorsz',
    'Divize': 'division',
    'kdy': 'when',
    'kdo': 'who',
    's kým': 'with_who',
    'celkem': 'total_time',
    'V/P/R': 'W/L/T',
    'překážky': 'hurdles',
    'jméno': 'name',
    'start': 'start',
    '1.pes': '1_dog',
    'jméno.1': 'name_1',
    'stříd.': 'chng',
    '2.pes': '2_dog',
    'jméno.2': 'name_2',
    'stříd..1': 'chng_1',
    '3.pes': '3_dog',
    'jméno.3': 'name_3',
    'stříd..2': 'chng_2',
    '4.pes': '4_dog',
    'event_place': 'event_place'
}

# Oszlopnevek átnevezése
df_CZ.rename(columns=new_column_names, inplace=True)
li(df_CZ)

használat: li(df)  # Használja az 'enter' változó értékét ha létezik és nagyobb mint 0, különben az összes sort megjeleníti vagy li(df, -1)
használat: li(df)  # Használja az 'enter' változó értékét ha létezik és nagyobb mint 0, különben az összes sort megjeleníti vagy li(df, -1)


In [21]:
# összevetés egyezik-e
di(df_EFC.head())
di(df_CZ.head())

In [22]:
# a két dataframe egyesítése oszlopok mentén

df_EFC_CZ = pd.concat([df_EFC, df_CZ], ignore_index=True)
di(df_EFC_CZ.head(6))
di(df_EFC_CZ.tail(6))

In [23]:
#240505 "NaN" értékek listázása különböző oszlopokban
nan_found = False

for column in df_EFC_CZ.columns:
    nan_rows = df_EFC_CZ[df_EFC_CZ[column].isna()]
    if not nan_rows.empty:
        nan_found = True
        print(f"NaN érték(ek) az '{column}' oszlopban:")
        print(nan_rows)
        print("\n")

if not nan_found:
    print("Nincs NaN érték az adatkeretben.")


NaN érték(ek) az 'sorsz' oszlopban:
      sorsz  division when  who with_who  total_time W/L/T  hurdles name  start 1_dog name_1 chng 2_dog name_2 chng_1 3_dog name_3 chng_2 4_dog                                     event_place
1723    NaN       NaN  NaN  NaN      NaN         NaN   NaN      NaN  NaN    NaN   NaN    NaN  NaN   NaN    NaN    NaN   NaN    NaN    NaN   NaN  Eager´s Cup 1. ring (Žamberk) 2023. május 6-7.
2382    NaN       NaN  NaN  NaN      NaN         NaN   NaN      NaN  NaN    NaN   NaN    NaN  NaN   NaN    NaN    NaN   NaN    NaN    NaN   NaN  Eager´s Cup 2. ring (Žamberk) 2023. május 6-7.


NaN érték(ek) az 'division' oszlopban:
      sorsz  division when  who with_who  total_time W/L/T  hurdles name  start 1_dog name_1 chng 2_dog name_2 chng_1 3_dog name_3 chng_2 4_dog                                     event_place
1723    NaN       NaN  NaN  NaN      NaN         NaN   NaN      NaN  NaN    NaN   NaN    NaN  NaN   NaN    NaN    NaN   NaN    NaN    NaN   NaN  Eager´s Cu

### ezt a kettő sort mindenképp el kell dobni, akadályozzák a tovább feldolgozást és információ értékük nulla.

1723         NaN         NaN   NaN   NaN      NaN  NaN    NaN   NaN    NaN  NaN   NaN    NaN    NaN   NaN    NaN    NaN   NaN  Eager´s Cup 1. ring (Žamberk) 2023. május 6-7.
2382         NaN         NaN   NaN      NaN  NaN    NaN   NaN    NaN  NaN   NaN    NaN    NaN   NaN    NaN    NaN   NaN  Eager´s Cup 2. ring (Žamberk) 2023. május 6-7.

Későbbi fázisban kitalálom mi legyen a többi "NaN" sorsa

In [24]:
# megtartom a régi df-et is
df_EFC_CZ_cleaned=df_EFC_CZ

In [25]:
#input_value = input("Kérem nyomjon billentyűt a 1723, 2382 sorok törléséhez, ez a sor csak teszteléshez kellett")
df_EFC_CZ_cleaned.drop(1723, inplace=True)
df_EFC_CZ_cleaned.drop(2382, inplace=True)

nan_found = False

for column in df_EFC_CZ.columns:
    nan_rows = df_EFC_CZ[df_EFC_CZ[column].isna()]
    if not nan_rows.empty:
        nan_found = True
        print(f"NaN érték(ek) az '{column}' oszlopban:")
        print(nan_rows)
        print("\n")

if not nan_found:
    print("Nincs NaN érték az adatkeretben.")

NaN érték(ek) az 'W/L/T' oszlopban:
      sorsz  division                 when                        who                  with_who  total_time W/L/T  hurdles    name  start 1_dog  name_1   chng 2_dog   name_2 chng_1 3_dog    name_3 chng_2 4_dog                                              event_place
94     95.0      11.0  1900-01-01 14:14:36        Roadrunners Rockets         The Green Chasers       19.39   NaN     15.0   Oswin  0.200   4.2   Djazz     ok  4.82     Waps    0.2  5.32      Vada    0.8  3.86         EFC - Ring 1 (Tápiószentmárton) 2023. július 29.
95     96.0      11.0  1900-01-01 14:14:36          The Green Chasers       Roadrunners Rockets       19.10   NaN      NaN     NaN  0.120  4.71     NaN   0.17  4.62      NaN   0.17  4.85       NaN   0.66   3.8         EFC - Ring 1 (Tápiószentmárton) 2023. július 29.
473    11.0       4.0  1900-01-01 08:14:26        Reinforced Concrete                Quickstep!       16.75   NaN     25.0    Aria -0.001  3.86    Prim   0.41  3.9

###Később döntök a "NaN" értékek sorsáról

In [26]:
#240507 a "when" oszlopot két oszlopra bontjuk 'when_date' és 'when_time'. Később majd helyre is tesszük bennük az adatokat.

# Ha nincs 'when' oszlop, térjünk vissza hibaüzenettel
if 'when' not in df_EFC_CZ_cleaned.columns:
    print("Error: 'when' column not found in DataFrame.")
    exit()

# 'when' oszlop értékeinek másolása a 'when_date' és 'when_time' oszlopokba
df_EFC_CZ_cleaned['when_date'] = df_EFC_CZ_cleaned['when']
df_EFC_CZ_cleaned['when_time'] = df_EFC_CZ_cleaned['when']

# Az "1900-01-01" tartalmazása esetén csak az idő kerül a 'when_time' oszlopba
# Ellenőrizzük, hogy az 'when' oszlop tartalmaz-e NaN vagy NA értékeket
if df_EFC_CZ_cleaned['when'].isnull().any():
    # NaN vagy NA értékek esetén helyettesítsük azokat "NA" stringgel
    df_EFC_CZ_cleaned['when'] = df_EFC_CZ_cleaned['when'].fillna("NA")

# Az "1900-01-01" tartalmazása esetén csak az idő kerül a 'when_time' oszlopba
df_EFC_CZ_cleaned.loc[df_EFC_CZ_cleaned['when'].str.contains("1900-01-01"), 'when_time'] = df_EFC_CZ_cleaned['when'].str.split(' ', n=1, expand=True)[1]

# Eredmény ellenőrzése
di(df_EFC_CZ_cleaned.head(10))
di(df_EFC_CZ_cleaned.tail(10))



In [27]:
# 20240329 ez jó szöveges dátumot csinál a 'when_date'-be
import pandas as pd
import re

def extract_dates(df):
    # Ellenőrizzük, hogy van-e "event_place" oszlop
    if 'event_place' not in df.columns:
        print("Error: 'event_place' column not found in DataFrame.")
        return None

    # Az "event_place" oszlop feldolgozása
    df['when_date'] = df['event_place'].apply(lambda x: x[x.find('2023'):].strip() if '2023' in str(x) else None)

    return df

# Tesztelés
#df_EFC_CZ_merged = pd.read_csv("df_EFC_CZ_merged.csv")
df_with_dates = extract_dates(df_EFC_CZ_cleaned)
di(df_with_dates.head(30))


In [28]:
#240329 ez jó számos dátumot csinál
import pandas as pd

def convert_date_format(date_string):
    # A magyar hónapok angol megfelelői
    month_translations = {
        'január': '01',
        'február': '02',
        'március': '03',
        'április': '04',
        'május': '05',
        'június': '06',
        'július': '07',
        'augusztus': '08',
        'szeptember': '09',
        'október': '10',
        'november': '11',
        'december': '12'
    }

    # A dátum string feldarabolása a kötőjel mentén
    parts = date_string.split('-')

    # Az első rész tartalmazza az eredeti dátumot
    original_date = parts[0].strip()

    # Az első rész további részeinek feldarabolása
    original_date_parts = original_date.split()
    if len(original_date_parts) == 3:
        # Az év, hónap és nap kinyerése
        year = original_date_parts[0].strip('.')
        month = original_date_parts[1].strip().lower()  # Hónap kisbetűsítése
        day = original_date_parts[2].strip('.')

        # Hónapok fordítása szám formátumra
        if month in month_translations:
            month = month_translations[month]

        # Dátum formátum szerinti értelmezése
        try:
            parsed_date = pd.to_datetime(f"{year}-{month}-{day}")
            return parsed_date.strftime('%Y-%m-%d')
        except ValueError:
            print(f"Failed to parse date: {original_date}")
            return None
    else:
        print(f"Failed to parse date: {original_date}")
        return None

# 'when_date' átalakítása
df_with_dates['when_date'] = df_with_dates['when_date'].apply(convert_date_format)
di(df_with_dates.head(20))
di(df_with_dates.tail(20))

In [29]:
# 240330 ez a jó kék-piros pálya felcimkézés, logikailag ugyan nem ide tartozik, de már nincs időm más helyre áthelyezni
def add_track_column(df, rows):
    # Ellenőrizzük, hogy van-e "when_time" oszlop
    if 'when' not in df.columns:
        print("Error: 'when' column not found in DataFrame.")
        return None

    # "track" oszlop inicializálása üres listával
    track_column = []

    # Az egyedi dátum-idő párok kigyűjtése az adott sorokra korlátozva
    unique_datetime_pairs = df.loc[rows, 'when'].unique()

    # Az egyedi dátum-idő párokhoz tartozó "track" értékek meghatározása
    for datetime_pair in unique_datetime_pairs:
        # Az aktuális dátum-idő párhoz tartozó indexek lekérdezése
        indices = df.index[(df.loc[rows, 'when'] == datetime_pair)].tolist()

        # Az azonos dátum-idő párokhoz tartozó "track" érték meghatározása
        track = None
        for i, index in enumerate(indices):
            if track is None:
                track = "kék"
            else:
                track = "piros"
            track_column.append(track)

    # Ellenőrizzük a rows változó hosszát
    print(len(rows))
    # Ellenőrizzük, hogy a track_column hossza egyezik-e a DataFrame hosszával
    if len(track_column) != len(rows):
        print("Error: Length of 'track_column' does not match length of specified rows.")
        return None

    # "track" oszlop hozzáadása a DataFrame-hez az adott sorokon belül
    df.loc[rows, 'track'] = track_column

    return df

# Az adott sorok kiválasztása
rows = df_with_dates['when'].notna()

# "track" oszlop hozzáadása a DataFrame-hez az adott sorokon belül
df_EFC_CZ_track = add_track_column(df_with_dates, rows)

# Eredmény kiíratása és megnézem mindenhova csak ez a két érték került
li(df_EFC_CZ_track,20)
luv(df_EFC_CZ_track, columns=['track'])

8571


használat: li(df)  # Használja az 'enter' változó értékét ha létezik és nagyobb mint 0, különben az összes sort megjeleníti vagy li(df, -1)
PARAMÉTEREZÉS: luv(dataframe, list_values=10, columns=["column1", "column2", ...], dtype="all/object/int64/float64/datetime64", search_value="valami")  = list_unique_values(dataframe)
Egyedi értékek a(z) 'track' 'oszlopban', (melynek típusa: object) (összesen: 2 db) (sorok száma: 8571)


Sorok száma: 8571



In [30]:
# korábban baj volt az index folytonosságával, ezt nézem meg
def find_discontinuous_indices(df):
    index_values = df.index.values
    discontinuous_indices = [index_values[i] for i in range(1, len(index_values)) if index_values[i] != index_values[i-1] + 1]
    return discontinuous_indices


# Függvény hívása
discontinuous_indices = find_discontinuous_indices(df_EFC_CZ_track)
print("Nem folytonos indexek:", discontinuous_indices)

Nem folytonos indexek: [1724, 2383]


In [31]:
# látszik hogy az index hiányos így, újraépítjük
#df_EFC_CZ_track = df_EFC_CZ_track.reindex(range(len(df_EFC_CZ)))
#df_EFC_CZ_track = df_EFC_CZ_track.sort_index()
df_EFC_CZ_track = df_EFC_CZ_track.reset_index(drop=True)

di(df_EFC_CZ_track.head(20))
di(df_EFC_CZ_track.tail(20))

In [32]:
discontinuous_indices = find_discontinuous_indices(df_EFC_CZ_track)
print("Nem folytonos indexek:", discontinuous_indices)

Nem folytonos indexek: []


####Látszik, hogy "when_date" a sok helyen kötőjeles, két napos dátumoknál csak az első dátumot tartalmaza. Ezt az alábbi függvény hivatott javítani.


Ez a kód egy DataFrame-en (df) végigmegy, és ellenőrzi az időpontokat. Ha az aktuális időpont (current_time) kisebb, mint az előző időpont (previous_time) ugyanazon a napon (previous_date==current_date), akkor kiírja az aktuális és az előző időpontot, majd hozzáad egy napot az aktuális dátumhoz. Ezután frissíti az when_date oszlopot a DataFrame-ben az új dátummal (new_date).

Ha az aktuális időpont nagyobb, mint az előző időpont, akkor az aktuális sor dátumát az előző sor dátumára állítja vissza.

In [33]:
#240419 most jó lett, a "when_date"-t korrigálja más oszlopok változásinak függvényében.  (végig ellenőriztem hibátlan)
from datetime import datetime, timedelta

def check_and_update_dates(df):
    previous_time = None
    previous_date = None
    previous_place = None
    for index, row in df.iterrows():
        current_time = row['when_time']
        current_date = row['when_date']
        current_place = df.at[index, 'event_place']
        if previous_time is not None and current_time < previous_time and previous_date==current_date and index > 1061:
            print(f"A(z) curr:{current_date}  prev:{previous_date}    dátumhoz tartozó idő kisebb, mint az előző időpont   cur:{current_time}  prev:{previous_time}   {current_place}.")
            datum = datetime.strptime(current_date, "%Y-%m-%d")
            uj_datum = datum + timedelta(days=1)
            current_date = uj_datum.strftime("%Y-%m-%d")
            print(current_date)

            new_date = current_date
            df.at[index, 'when_date'] = new_date
        elif previous_time is not None and current_time >= previous_time and previous_place==current_place:

            df.at[index, 'when_date'] = df.at[index - 1, 'when_date']
        previous_time = current_time
        previous_date = current_date
        previous_place = current_place

check_and_update_dates(df_EFC_CZ_track)

#di(df_EFC_CZ_track.tail(10))

A(z) curr:2023-04-22  prev:2023-04-22    dátumhoz tartozó idő kisebb, mint az előző időpont   cur:09:06:03  prev:17:17:12   Hanácké škvarek (Heroltice) 2023. április 22-23..
2023-04-23
A(z) curr:2023-05-06  prev:2023-05-06    dátumhoz tartozó idő kisebb, mint az előző időpont   cur:08:12:17  prev:18:28:21   Eager´s Cup 1. ring (Žamberk) 2023. május 6-7..
2023-05-07
A(z) curr:2023-05-06  prev:2023-05-06    dátumhoz tartozó idő kisebb, mint az előző időpont   cur:09:24:34  prev:18:07:41   Eager´s Cup 2. ring (Žamberk) 2023. május 6-7..
2023-05-07
A(z) curr:2023-05-06  prev:2023-05-06    dátumhoz tartozó idő kisebb, mint az előző időpont   cur:08:13:18  prev:18:08:53   Eager´s Cup 2. ring (Žamberk) 2023. május 6-7..
2023-05-07
A(z) curr:2023-05-20  prev:2023-05-20    dátumhoz tartozó idő kisebb, mint az előző időpont   cur:08:10:18  prev:17:31:03   Flyvaryors turnaj (Blšany) 2023. május 20-21..
2023-05-21
A(z) curr:2023-06-10  prev:2023-06-10    dátumhoz tartozó idő kisebb, mint az előző 

In [34]:
# a korrekció ellenőrzése, azok a sorok ahol változott a 'when_date'
def print_changed_rows(df, column):
    changed_indices = df[df[column].ne(df[column].shift())].index
    filtered_df = df.loc[changed_indices]
    di(filtered_df)

print_changed_rows(df_EFC_CZ_track, 'when_date')

In [35]:
# ha teljes listát akarok nézni
#di(df_EFC_CZ_track)

In [36]:
# a korrekció ellenőrzése szintén, egyedi értékek
luv(df_EFC_CZ_track, list_values=1000, columns=["event_place", "when_date"], dtype="all", search_value=None)

PARAMÉTEREZÉS: luv(dataframe, list_values=10, columns=["column1", "column2", ...], dtype="all/object/int64/float64/datetime64", search_value="valami")  = list_unique_values(dataframe)
Egyedi értékek a(z) 'event_place' 'oszlopban', (melynek típusa: object) (összesen: 16 db) (sorok száma: 8571)


Sorok száma: 8571

PARAMÉTEREZÉS: luv(dataframe, list_values=10, columns=["column1", "column2", ...], dtype="all/object/int64/float64/datetime64", search_value="valami")  = list_unique_values(dataframe)
Egyedi értékek a(z) 'when_date' 'oszlopban', (melynek típusa: object) (összesen: 22 db) (sorok száma: 8571)


Sorok száma: 8571



In [37]:
# jelenlegi jellemzők
dinfo(df_EFC_CZ_track)


DataFrame oszlopainak statisztikái:


In [38]:
# ha részletesebb egyedi értékekre voltam kíváncsi
list_unique_values(df_EFC_CZ_track, list_values=10)

PARAMÉTEREZÉS: luv(dataframe, list_values=10, columns=["column1", "column2", ...], dtype="all/object/int64/float64/datetime64", search_value="valami")  = list_unique_values(dataframe)
Egyedi értékek a(z) '1_dog' 'oszlopban', (melynek típusa: object) (összesen: 276 db) (sorok száma: 8571)


Sorok száma: 8571

PARAMÉTEREZÉS: luv(dataframe, list_values=10, columns=["column1", "column2", ...], dtype="all/object/int64/float64/datetime64", search_value="valami")  = list_unique_values(dataframe)
Egyedi értékek a(z) '2_dog' 'oszlopban', (melynek típusa: object) (összesen: 357 db) (sorok száma: 8571)


Sorok száma: 8571

PARAMÉTEREZÉS: luv(dataframe, list_values=10, columns=["column1", "column2", ...], dtype="all/object/int64/float64/datetime64", search_value="valami")  = list_unique_values(dataframe)
Egyedi értékek a(z) '3_dog' 'oszlopban', (melynek típusa: object) (összesen: 374 db) (sorok száma: 8571)


Sorok száma: 8571

PARAMÉTEREZÉS: luv(dataframe, list_values=10, columns=["column1", "column2", ...], dtype="all/object/int64/float64/datetime64", search_value="valami")  = list_unique_values(dataframe)
Egyedi értékek a(z) '4_dog' 'oszlopban', (melynek típusa: object) (összesen: 434 db) (sorok száma: 8571)


Sorok száma: 8571

PARAMÉTEREZÉS: luv(dataframe, list_values=10, columns=["column1", "column2", ...], dtype="all/object/int64/float64/datetime64", search_value="valami")  = list_unique_values(dataframe)
Egyedi értékek a(z) 'W/L/T' 'oszlopban', (melynek típusa: object) (összesen: 6 db) (sorok száma: 8571)


Sorok száma: 8571

PARAMÉTEREZÉS: luv(dataframe, list_values=10, columns=["column1", "column2", ...], dtype="all/object/int64/float64/datetime64", search_value="valami")  = list_unique_values(dataframe)
Egyedi értékek a(z) 'chng' 'oszlopban', (melynek típusa: object) (összesen: 229 db) (sorok száma: 8571)


Sorok száma: 8571

PARAMÉTEREZÉS: luv(dataframe, list_values=10, columns=["column1", "column2", ...], dtype="all/object/int64/float64/datetime64", search_value="valami")  = list_unique_values(dataframe)
Egyedi értékek a(z) 'chng_1' 'oszlopban', (melynek típusa: object) (összesen: 252 db) (sorok száma: 8571)


Sorok száma: 8571

PARAMÉTEREZÉS: luv(dataframe, list_values=10, columns=["column1", "column2", ...], dtype="all/object/int64/float64/datetime64", search_value="valami")  = list_unique_values(dataframe)
Egyedi értékek a(z) 'chng_2' 'oszlopban', (melynek típusa: object) (összesen: 415 db) (sorok száma: 8571)


Sorok száma: 8571

PARAMÉTEREZÉS: luv(dataframe, list_values=10, columns=["column1", "column2", ...], dtype="all/object/int64/float64/datetime64", search_value="valami")  = list_unique_values(dataframe)
Egyedi értékek a(z) 'division' 'oszlopban', (melynek típusa: float64) (összesen: 13 db) (sorok száma: 8571)


Sorok száma: 8571

PARAMÉTEREZÉS: luv(dataframe, list_values=10, columns=["column1", "column2", ...], dtype="all/object/int64/float64/datetime64", search_value="valami")  = list_unique_values(dataframe)
Egyedi értékek a(z) 'event_place' 'oszlopban', (melynek típusa: object) (összesen: 16 db) (sorok száma: 8571)


Sorok száma: 8571

PARAMÉTEREZÉS: luv(dataframe, list_values=10, columns=["column1", "column2", ...], dtype="all/object/int64/float64/datetime64", search_value="valami")  = list_unique_values(dataframe)
Egyedi értékek a(z) 'hurdles' 'oszlopban', (melynek típusa: float64) (összesen: 8 db) (sorok száma: 8571)


Sorok száma: 8571

PARAMÉTEREZÉS: luv(dataframe, list_values=10, columns=["column1", "column2", ...], dtype="all/object/int64/float64/datetime64", search_value="valami")  = list_unique_values(dataframe)
Egyedi értékek a(z) 'name' 'oszlopban', (melynek típusa: object) (összesen: 268 db) (sorok száma: 8571)


Sorok száma: 8571

PARAMÉTEREZÉS: luv(dataframe, list_values=10, columns=["column1", "column2", ...], dtype="all/object/int64/float64/datetime64", search_value="valami")  = list_unique_values(dataframe)
Egyedi értékek a(z) 'name_1' 'oszlopban', (melynek típusa: object) (összesen: 277 db) (sorok száma: 8571)


Sorok száma: 8571

PARAMÉTEREZÉS: luv(dataframe, list_values=10, columns=["column1", "column2", ...], dtype="all/object/int64/float64/datetime64", search_value="valami")  = list_unique_values(dataframe)
Egyedi értékek a(z) 'name_2' 'oszlopban', (melynek típusa: object) (összesen: 301 db) (sorok száma: 8571)


Sorok száma: 8571

PARAMÉTEREZÉS: luv(dataframe, list_values=10, columns=["column1", "column2", ...], dtype="all/object/int64/float64/datetime64", search_value="valami")  = list_unique_values(dataframe)
Egyedi értékek a(z) 'name_3' 'oszlopban', (melynek típusa: object) (összesen: 298 db) (sorok száma: 8571)


Sorok száma: 8571

PARAMÉTEREZÉS: luv(dataframe, list_values=10, columns=["column1", "column2", ...], dtype="all/object/int64/float64/datetime64", search_value="valami")  = list_unique_values(dataframe)
Egyedi értékek a(z) 'sorsz' 'oszlopban', (melynek típusa: float64) (összesen: 824 db) (sorok száma: 8571)


Sorok száma: 8571

PARAMÉTEREZÉS: luv(dataframe, list_values=10, columns=["column1", "column2", ...], dtype="all/object/int64/float64/datetime64", search_value="valami")  = list_unique_values(dataframe)
Egyedi értékek a(z) 'start' 'oszlopban', (melynek típusa: float64) (összesen: 194 db) (sorok száma: 8571)


Sorok száma: 8571

PARAMÉTEREZÉS: luv(dataframe, list_values=10, columns=["column1", "column2", ...], dtype="all/object/int64/float64/datetime64", search_value="valami")  = list_unique_values(dataframe)
Egyedi értékek a(z) 'total_time' 'oszlopban', (melynek típusa: float64) (összesen: 1909 db) (sorok száma: 8571)


Sorok száma: 8571

PARAMÉTEREZÉS: luv(dataframe, list_values=10, columns=["column1", "column2", ...], dtype="all/object/int64/float64/datetime64", search_value="valami")  = list_unique_values(dataframe)
Egyedi értékek a(z) 'track' 'oszlopban', (melynek típusa: object) (összesen: 2 db) (sorok száma: 8571)


Sorok száma: 8571

PARAMÉTEREZÉS: luv(dataframe, list_values=10, columns=["column1", "column2", ...], dtype="all/object/int64/float64/datetime64", search_value="valami")  = list_unique_values(dataframe)
Egyedi értékek a(z) 'when' 'oszlopban', (melynek típusa: object) (összesen: 4120 db) (sorok száma: 8571)


Sorok száma: 8571

PARAMÉTEREZÉS: luv(dataframe, list_values=10, columns=["column1", "column2", ...], dtype="all/object/int64/float64/datetime64", search_value="valami")  = list_unique_values(dataframe)
Egyedi értékek a(z) 'when_date' 'oszlopban', (melynek típusa: object) (összesen: 22 db) (sorok száma: 8571)


Sorok száma: 8571

PARAMÉTEREZÉS: luv(dataframe, list_values=10, columns=["column1", "column2", ...], dtype="all/object/int64/float64/datetime64", search_value="valami")  = list_unique_values(dataframe)
Egyedi értékek a(z) 'when_time' 'oszlopban', (melynek típusa: object) (összesen: 4066 db) (sorok száma: 8571)


Sorok száma: 8571

PARAMÉTEREZÉS: luv(dataframe, list_values=10, columns=["column1", "column2", ...], dtype="all/object/int64/float64/datetime64", search_value="valami")  = list_unique_values(dataframe)
Egyedi értékek a(z) 'who' 'oszlopban', (melynek típusa: object) (összesen: 139 db) (sorok száma: 8571)


Sorok száma: 8571

PARAMÉTEREZÉS: luv(dataframe, list_values=10, columns=["column1", "column2", ...], dtype="all/object/int64/float64/datetime64", search_value="valami")  = list_unique_values(dataframe)
Egyedi értékek a(z) 'with_who' 'oszlopban', (melynek típusa: object) (összesen: 139 db) (sorok száma: 8571)


Sorok száma: 8571



In [39]:
#li(df_EFC_CZ_track,9)

In [40]:
# a "sorsz" oszlop int64 típusra konvertálása
df_EFC_CZ_track['sorsz'] = df_EFC_CZ_track['sorsz'].astype('int64')
print(df_EFC_CZ_track['sorsz'].dtype)

int64


In [52]:
# áttekintő hisztogramok a numerikus oszlopokról
plot_histograms(df_EFC_CZ_track)
print(df_EFC_CZ_track)

TypeError: unhashable type: 'DataFrame'

In [42]:
import numpy as np  # NumPy importálása
from scipy import stats  # Scipy importálása a statisztikai műveletekhez

def numeric_column_summary_statistics_full(df):
    # Az összes oszlop fejlécének kiválasztása
    all_columns = df.columns

    # Csak a számot tartalmazó oszlopok kiválasztása
    numeric_columns = df.select_dtypes(include='number').columns

    # Statisztikák kiszámolása minden oszlopra
    statistics = pd.DataFrame(index=['Min', 'Max', 'Átlag', 'Medián', 'Modusz', 'Variabilitás', 'Alsó Kvantil', 'Felső Kvantil',
                                     'Korreláció', 'Kovariancia', 'Százalékos Változás', 'Konfidencia-intervallumok',
                                     'Lineáris Regresszió Együtthatók'], columns=all_columns)

    for column in all_columns:
        if column in numeric_columns:
            statistics.at['Min', column] = df[column].min()
            statistics.at['Max', column] = df[column].max()
            statistics.at['Átlag', column] = df[column].mean()
            statistics.at['Medián', column] = df[column].median()
            statistics.at['Modusz', column] = df[column].mode().iloc[0]  # Modusz számítása
            statistics.at['Variabilitás', column] = df[column].std()  # Szórás
            statistics.at['Alsó Kvantil', column] = df[column].quantile(0.25)  # Alsó kvantil
            statistics.at['Felső Kvantil', column] = df[column].quantile(0.75)  # Felső kvantil
            # Korreláció és kovariancia kiszámítása a többi oszloppal
            for other_column in numeric_columns:
                if other_column != column:
                    statistics.at['Korreláció', column] = df[column].corr(df[other_column])
                    statistics.at['Kovariancia', column] = df[column].cov(df[other_column])
            # Százalékos változás számítása
            first_value = df[column].iloc[0]
            last_value = df[column].iloc[-1]
            statistics.at['Százalékos Változás', column] = ((last_value - first_value) / first_value) * 100
            # Konfidencia-intervallumok
            confidence_interval = stats.norm.interval(0.95, loc=df[column].mean(), scale=df[column].std())
            statistics.at['Konfidencia-intervallumok', column] = confidence_interval
            # Lineáris regresszió együtthatók
            # Ez csak egy példa, itt valószínűleg több munka és elemzés kellene
            slope, intercept, r_value, p_value, std_err = stats.linregress(df[column], df['start'])
            statistics.at['Lineáris Regresszió Együtthatók', column] = (slope, intercept, r_value, p_value, std_err)
        else:
            # Nem szám típusú oszlopoknak NaN értékeket adunk
            statistics.at['Min', column] = np.nan
            statistics.at['Max', column] = np.nan
            statistics.at['Átlag', column] = np.nan
            statistics.at['Medián', column] = np.nan
            statistics.at['Modusz', column] = np.nan
            statistics.at['Variabilitás', column] = np.nan
            statistics.at['Alsó Kvantil', column] = np.nan
            statistics.at['Felső Kvantil', column] = np.nan
            statistics.at['Korreláció', column] = np.nan
            statistics.at['Kovariancia', column] = np.nan
            statistics.at['Százalékos Változás', column] = np.nan
            statistics.at['Konfidencia-intervallumok', column] = np.nan
            statistics.at['Lineáris Regresszió Együtthatók', column] = np.nan

    # Statisztikák kiíratása
    print("Összefoglaló statisztikák minden oszlopra:")
    display(statistics)

numeric_column_summary_statistics_full(df_EFC_CZ_track)

Összefoglaló statisztikák minden oszlopra:


sorsz                                                                                                       division when  who with_who                                                                                                        total_time W/L/T                                  hurdles name                                      start 1_dog name_1 chng 2_dog name_2 chng_1 3_dog name_3 chng_2 4_dog event_place when_date when_time track
Min                                                                                                                                             1                                                                                                            1.0  NaN  NaN      NaN                                                                                                               0.0   NaN                                     15.0  NaN                                      -1.55   NaN    NaN  NaN   NaN    NaN    NaN   NaN    NaN    NaN   NaN         NaN       NaN       NaN   NaN
Max                                                                                                                                           824                                                                                                           13.0  NaN  NaN      NaN                                                                                                             86.03   NaN                                     32.5  NaN                                      25.58   NaN    NaN  NaN   NaN    NaN    NaN   NaN    NaN    NaN   NaN         NaN       NaN       NaN   NaN
Átlag                                                                                                                                  305.887528                                                                                                       3.782406  NaN  NaN      NaN                                                                                                          19.75251   NaN                                22.712778  NaN                                   0.117333   NaN    NaN  NaN   NaN    NaN    NaN   NaN    NaN    NaN   NaN         NaN       NaN       NaN   NaN
Medián                                                                                                                                      277.0                                                                                                            3.0  NaN  NaN      NaN                                                                                                             18.27   NaN                                     22.5  NaN                                       0.09   NaN    NaN  NaN   NaN    NaN    NaN   NaN    NaN    NaN   NaN         NaN       NaN       NaN   NaN
Modusz                                                                                                                                          5                                                                                                            1.0  NaN  NaN      NaN                                                                                                             18.05   NaN                                     27.5  NaN                                       0.09   NaN    NaN  NaN   NaN    NaN    NaN   NaN    NaN    NaN   NaN         NaN       NaN       NaN   NaN
Variabilitás                                                                                                                            202.12014                                                                                                       2.626434  NaN  NaN      NaN                                                                                                          6.086355   NaN                                 4.499043  NaN                                   0.575569   NaN    NaN  NaN   NaN    NaN    NaN   NaN    NaN    NaN   NaN         NaN       NaN       NaN   NaN
Alsó Kvantil                   

In [43]:
# Írás CSV fájlba
csv_output_path = "df_EFC_CZ_track_good-date.csv"
df_EFC_CZ_track.to_csv(csv_output_path, index=False)

# Ellenőrzés
print(f"DataFrame successfully written to {csv_output_path}.")

DataFrame successfully written to df_EFC_CZ_track_good-date.csv.


In [44]:
import pandas as pd

# DataFrame beolvasása CSV fájlból
df_EFC_CZ_merged = pd.read_csv("df_EFC_CZ_track_good-date.csv")

# Az adatok megjelenítése
li(df_EFC_CZ_merged)

használat: li(df)  # Használja az 'enter' változó értékét ha létezik és nagyobb mint 0, különben az összes sort megjeleníti vagy li(df, -1)


In [45]:
dinfo(df_EFC_CZ_merged)


DataFrame oszlopainak statisztikái:


#Következik a: Flyball_EFC_CZ_post_analyzing_XXXXXX.ipynb